/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VALIDATOR_H_RPCGEN
#define _VALIDATOR_H_RPCGEN

//##include <rpc/rpc.h>
#include <tirpc/rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct point {
	float x;
	float y;
	float z;
	int r;
	int g;
	int b;
};
typedef struct point point;

#define PVAL 0x2fffffff
#define VALIDATOR 1

#if defined(__STDC__) || defined(__cplusplus)
#define VALIDATE_POINT 1
extern  int * validate_point_1(point *, CLIENT *);
extern  int * validate_point_1_svc(point *, struct svc_req *);
extern int pval_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define VALIDATE_POINT 1
extern  int * validate_point_1();
extern  int * validate_point_1_svc();
extern int pval_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_point (XDR *, point*);

#else /* K&R C */
extern bool_t xdr_point ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VALIDATOR_H_RPCGEN */
