/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCY_H_RPCGEN
#define _RPCY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define RPCE 0x2fffffff
#define RPC_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define TEST 1
extern  int * test_1(void *, CLIENT *);
extern  int * test_1_svc(void *, struct svc_req *);
extern int rpce_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define TEST 1
extern  int * test_1();
extern  int * test_1_svc();
extern int rpce_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCY_H_RPCGEN */
